### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by y-takey** [y-takey/shokushu#2]
- [x] save last viewed date, and count up viewing.
- [x] recommend favorite a video. e.g.) has 4 stars or more, and has same the tag, or the video title is similar
- [x] when return from playing screen, restoration scroll position on list
